import { Badge } from "../ui/badge";

const colorMap: Record<string, string> = {
  DRAFT: "bg-slate-100 text-slate-700 border-transparent",
  SUBMITTED: "bg-blue-100 text-blue-700 border-transparent",
  APPROVED: "bg-emerald-100 text-emerald-700 border-transparent",
  SENT: "bg-blue-100 text-blue-700 border-transparent",
  ACCEPTED: "bg-emerald-100 text-emerald-700 border-transparent",
  REJECTED: "bg-rose-100 text-rose-700 border-transparent",
  REFUSED: "bg-rose-100 text-rose-700 border-transparent",
  EXPIRED: "bg-amber-100 text-amber-800 border-transparent",
  UNDER_REVIEW: "bg-violet-100 text-violet-700 border-transparent",
  ISSUED: "bg-amber-100 text-amber-800 border-transparent",
  OVERDUE: "bg-rose-100 text-rose-700 border-transparent",
  PAID: "bg-emerald-100 text-emerald-700 border-transparent",
  UNPAID: "bg-orange-100 text-orange-700 border-transparent",
  PARTIAL: "bg-amber-100 text-amber-800 border-transparent",
  PARTIALLY_PAID: "bg-amber-100 text-amber-800 border-transparent",
  CONFIRMED: "bg-emerald-100 text-emerald-700 border-transparent",
  PENDING: "bg-amber-100 text-amber-800 border-transparent",
  FAILED: "bg-rose-100 text-rose-700 border-transparent",
  REFUNDED: "bg-slate-100 text-slate-700 border-transparent",
  PREPARED: "bg-slate-100 text-slate-700 border-transparent",
  IN_TRANSIT: "bg-blue-100 text-blue-700 border-transparent",
  DELIVERED: "bg-emerald-100 text-emerald-700 border-transparent",
  NEW: "bg-slate-100 text-slate-700 border-transparent",
  CONTACTED: "bg-blue-100 text-blue-700 border-transparent",
  QUALIFIED: "bg-violet-100 text-violet-700 border-transparent",
  QUOTED: "bg-amber-100 text-amber-800 border-transparent",
  WON: "bg-emerald-100 text-emerald-700 border-transparent",
  LOST: "bg-rose-100 text-rose-700 border-transparent",
  IN_PROGRESS: "bg-orange-100 text-orange-700 border-transparent",
  COMPLETED: "bg-emerald-100 text-emerald-700 border-transparent",
  PLANNED: "bg-sky-100 text-sky-700 border-transparent",
  ON_HOLD: "bg-slate-100 text-slate-700 border-transparent",
  CANCELLED: "bg-rose-100 text-rose-700 border-transparent",
  ACTIVE: "bg-emerald-100 text-emerald-700 border-transparent",
  INACTIVE: "bg-slate-100 text-slate-700 border-transparent",
};

const labelMap: Record<string, string> = {
  DRAFT: "BROUILLON",
  SUBMITTED: "SOUMISE",
  APPROVED: "APPROUVEE",
  SENT: "ENVOYE",
  ACCEPTED: "ACCEPTE",
  REJECTED: "REJETE",
  REFUSED: "REFUSE",
  EXPIRED: "EXPIRE",
  UNDER_REVIEW: "EN REVISION",
  ISSUED: "EMISE",
  OVERDUE: "EN RETARD",
  PAID: "PAYE",
  UNPAID: "IMPAYE",
  PARTIAL: "PARTIEL",
  PARTIALLY_PAID: "PARTIELLEMENT PAYE",
  CONFIRMED: "CONFIRME",
  PENDING: "EN ATTENTE",
  FAILED: "ECHEC",
  REFUNDED: "REMBOURSE",
  PREPARED: "PREPARE",
  IN_TRANSIT: "EN TRANSIT",
  DELIVERED: "LIVRE",
  NEW: "NOUVEAU",
  CONTACTED: "CONTACTE",
  QUALIFIED: "QUALIFIE",
  QUOTED: "DEVIS ENVOYE",
  WON: "GAGNE",
  LOST: "PERDU",
  IN_PROGRESS: "EN COURS",
  COMPLETED: "TERMINE",
  PLANNED: "PLANIFIE",
  ON_HOLD: "EN ATTENTE",
  CANCELLED: "ANNULE",
  ACTIVE: "ACTIF",
  INACTIVE: "INACTIF",
};

export function StatusBadge({ status }: { status: string }) {
  return (
    <Badge variant="outline" className={colorMap[status] ?? "bg-secondary text-secondary-foreground border-transparent"}>
      {labelMap[status] ?? status.replaceAll("_", " ")}
    </Badge>
  );
}
