export type ScopePolicy = "tenant" | "branch" | "assigned" | "self";

export interface PermissionSeed {
  code: string;
  resource: string;
  action: string;
  label: string;
  description: string;
}

export interface RoleTemplateSeed {
  code: string;
  name: string;
  description: string;
  defaultScope: ScopePolicy;
  permissionCodes: string[];
}

export const permissionCatalog: PermissionSeed[] = [
  { code: "dashboard.read", resource: "dashboard", action: "read", label: "Read dashboard", description: "View dashboard KPIs, alerts, and overview widgets." },
  { code: "reports.read", resource: "reports", action: "read", label: "Read reports", description: "View reporting and analytical screens." },
  { code: "reports.export", resource: "reports", action: "export", label: "Export reports", description: "Export reporting datasets and summaries." },
  { code: "activity_logs.read", resource: "activity_logs", action: "read", label: "Read activity logs", description: "View operational activity logs." },
  { code: "audit_logs.read", resource: "audit_logs", action: "read", label: "Read audit logs", description: "View audit trails for security and data changes." },

  { code: "clients.read", resource: "clients", action: "read", label: "Read clients", description: "View client records." },
  { code: "clients.create", resource: "clients", action: "create", label: "Create clients", description: "Create new client records." },
  { code: "clients.update", resource: "clients", action: "update", label: "Update clients", description: "Edit client records." },
  { code: "clients.archive", resource: "clients", action: "archive", label: "Archive clients", description: "Archive or restore client records." },
  { code: "client_contacts.read", resource: "client_contacts", action: "read", label: "Read client contacts", description: "View client contact records." },
  { code: "client_contacts.create", resource: "client_contacts", action: "create", label: "Create client contacts", description: "Create client contact records." },
  { code: "client_contacts.update", resource: "client_contacts", action: "update", label: "Update client contacts", description: "Edit client contact records." },
  { code: "client_contacts.delete", resource: "client_contacts", action: "delete", label: "Delete client contacts", description: "Delete client contact records." },

  { code: "leads.read", resource: "leads", action: "read", label: "Read leads", description: "View prospect and lead records." },
  { code: "leads.create", resource: "leads", action: "create", label: "Create leads", description: "Create new leads." },
  { code: "leads.update", resource: "leads", action: "update", label: "Update leads", description: "Edit lead records." },
  { code: "leads.archive", resource: "leads", action: "archive", label: "Archive leads", description: "Archive or restore leads." },
  { code: "leads.convert", resource: "leads", action: "convert", label: "Convert leads", description: "Convert a lead into a client." },
  { code: "lead_activities.read", resource: "lead_activities", action: "read", label: "Read lead activities", description: "View lead activity timelines." },
  { code: "lead_activities.create", resource: "lead_activities", action: "create", label: "Create lead activities", description: "Add lead activities and reminders." },
  { code: "lead_activities.update", resource: "lead_activities", action: "update", label: "Update lead activities", description: "Edit lead activities and reminders." },
  { code: "notes.read", resource: "notes", action: "read", label: "Read notes", description: "Read internal notes on business records." },
  { code: "notes.create", resource: "notes", action: "create", label: "Create notes", description: "Add internal notes to business records." },
  { code: "notes.update", resource: "notes", action: "update", label: "Update notes", description: "Edit internal notes." },
  { code: "notes.delete", resource: "notes", action: "delete", label: "Delete notes", description: "Delete internal notes." },

  { code: "quotations.read", resource: "quotations", action: "read", label: "Read quotations", description: "View quotations and quotation history." },
  { code: "quotations.create", resource: "quotations", action: "create", label: "Create quotations", description: "Create quotations." },
  { code: "quotations.update", resource: "quotations", action: "update", label: "Update quotations", description: "Edit quotations in editable states." },
  { code: "quotations.send", resource: "quotations", action: "send", label: "Send quotations", description: "Send or mark quotations as sent." },
  { code: "quotations.approve", resource: "quotations", action: "approve", label: "Approve quotations", description: "Approve or accept quotations." },
  { code: "quotations.reject", resource: "quotations", action: "reject", label: "Reject quotations", description: "Reject quotations." },
  { code: "quotations.duplicate", resource: "quotations", action: "duplicate", label: "Duplicate quotations", description: "Duplicate quotations into new drafts." },
  { code: "quotations.export_pdf", resource: "quotations", action: "export_pdf", label: "Export quotation PDF", description: "Generate quotation PDF output." },
  { code: "quotations.convert", resource: "quotations", action: "convert", label: "Convert quotation", description: "Convert accepted quotations into projects or invoices." },

  { code: "invoices.read", resource: "invoices", action: "read", label: "Read invoices", description: "View invoices and invoice history." },
  { code: "invoices.create", resource: "invoices", action: "create", label: "Create invoices", description: "Create invoices manually or from source records." },
  { code: "invoices.update", resource: "invoices", action: "update", label: "Update invoices", description: "Edit draft invoices." },
  { code: "invoices.issue", resource: "invoices", action: "issue", label: "Issue invoices", description: "Issue invoices and finalize numbering." },
  { code: "invoices.void", resource: "invoices", action: "void", label: "Void invoices", description: "Void or cancel invoices." },
  { code: "invoices.export_pdf", resource: "invoices", action: "export_pdf", label: "Export invoice PDF", description: "Generate invoice PDF output." },

  { code: "payments.read", resource: "payments", action: "read", label: "Read payments", description: "View payment records and allocations." },
  { code: "payments.record", resource: "payments", action: "record", label: "Record payments", description: "Record incoming payments." },
  { code: "payments.allocate", resource: "payments", action: "allocate", label: "Allocate payments", description: "Allocate payments across invoices." },
  { code: "payments.update", resource: "payments", action: "update", label: "Update payments", description: "Edit payment metadata when allowed." },

  { code: "expenses.read", resource: "expenses", action: "read", label: "Read expenses", description: "View expenses and expense categories." },
  { code: "expenses.create", resource: "expenses", action: "create", label: "Create expenses", description: "Create expense records." },
  { code: "expenses.update", resource: "expenses", action: "update", label: "Update expenses", description: "Edit draft or allowed expenses." },
  { code: "expenses.approve", resource: "expenses", action: "approve", label: "Approve expenses", description: "Approve submitted expenses." },
  { code: "expenses.pay", resource: "expenses", action: "pay", label: "Pay expenses", description: "Mark expenses as paid." },

  { code: "delivery_notes.read", resource: "delivery_notes", action: "read", label: "Read delivery notes", description: "View delivery notes and delivery history." },
  { code: "delivery_notes.create", resource: "delivery_notes", action: "create", label: "Create delivery notes", description: "Create delivery notes." },
  { code: "delivery_notes.update", resource: "delivery_notes", action: "update", label: "Update delivery notes", description: "Edit delivery notes." },
  { code: "delivery_notes.change_status", resource: "delivery_notes", action: "change_status", label: "Change delivery status", description: "Change delivery note status." },
  { code: "delivery_notes.export_pdf", resource: "delivery_notes", action: "export_pdf", label: "Export delivery note PDF", description: "Generate printable delivery note output." },
  { code: "vehicles.read", resource: "vehicles", action: "read", label: "Read vehicles", description: "View logistics vehicle records." },
  { code: "vehicles.create", resource: "vehicles", action: "create", label: "Create vehicles", description: "Create vehicle records." },
  { code: "vehicles.update", resource: "vehicles", action: "update", label: "Update vehicles", description: "Edit vehicle records." },

  { code: "projects.read", resource: "projects", action: "read", label: "Read projects", description: "View project and chantier records." },
  { code: "projects.create", resource: "projects", action: "create", label: "Create projects", description: "Create projects manually or from quotations." },
  { code: "projects.update", resource: "projects", action: "update", label: "Update projects", description: "Edit project core data." },
  { code: "projects.change_status", resource: "projects", action: "change_status", label: "Change project status", description: "Update project lifecycle status." },
  { code: "projects.assign", resource: "projects", action: "assign", label: "Assign projects", description: "Assign people to projects." },
  { code: "project_stages.manage", resource: "project_stages", action: "manage", label: "Manage project stages", description: "Manage project stages and stage progress." },
  { code: "project_tasks.manage", resource: "project_tasks", action: "manage", label: "Manage project tasks", description: "Manage project tasks." },
  { code: "project_measurements.manage", resource: "project_measurements", action: "manage", label: "Manage project measurements", description: "Create and edit project measurements." },
  { code: "project_files.manage", resource: "project_files", action: "manage", label: "Manage project files", description: "Attach and organize project files." },

  { code: "files.read", resource: "files", action: "read", label: "Read files", description: "Read file metadata and attachments." },
  { code: "files.upload", resource: "files", action: "upload", label: "Upload files", description: "Upload documents and images." },
  { code: "files.link", resource: "files", action: "link", label: "Link files", description: "Attach files to entities." },
  { code: "files.delete", resource: "files", action: "delete", label: "Delete files", description: "Delete or detach files." },

  { code: "catalog.read", resource: "catalog", action: "read", label: "Read catalog", description: "Read products, services, categories, and units." },
  { code: "catalog.create", resource: "catalog", action: "create", label: "Create catalog", description: "Create products, services, categories, and units." },
  { code: "catalog.update", resource: "catalog", action: "update", label: "Update catalog", description: "Update products, services, categories, and units." },
  { code: "catalog.archive", resource: "catalog", action: "archive", label: "Archive catalog", description: "Archive catalog records." },

  { code: "users.read", resource: "users", action: "read", label: "Read users", description: "View user accounts." },
  { code: "users.create", resource: "users", action: "create", label: "Create users", description: "Create or invite users." },
  { code: "users.update", resource: "users", action: "update", label: "Update users", description: "Edit user accounts." },
  { code: "users.suspend", resource: "users", action: "suspend", label: "Suspend users", description: "Suspend or reactivate users." },
  { code: "roles.read", resource: "roles", action: "read", label: "Read roles", description: "View roles and their permissions." },
  { code: "roles.create", resource: "roles", action: "create", label: "Create roles", description: "Create custom roles." },
  { code: "roles.update", resource: "roles", action: "update", label: "Update roles", description: "Update role definitions." },
  { code: "permissions.read", resource: "permissions", action: "read", label: "Read permissions", description: "View the permission catalog." },
  { code: "settings.read", resource: "settings", action: "read", label: "Read settings", description: "Read application settings." },
  { code: "settings.update", resource: "settings", action: "update", label: "Update settings", description: "Update application settings." },
  { code: "numbering_sequences.read", resource: "numbering_sequences", action: "read", label: "Read numbering sequences", description: "View document numbering sequences." },
  { code: "numbering_sequences.update", resource: "numbering_sequences", action: "update", label: "Update numbering sequences", description: "Update document numbering rules." },
  { code: "sessions.read", resource: "sessions", action: "read", label: "Read sessions", description: "View refresh tokens or sessions." },
  { code: "sessions.revoke", resource: "sessions", action: "revoke", label: "Revoke sessions", description: "Revoke refresh tokens or sessions." },
];

const allPermissions = permissionCatalog.map((permission) => permission.code);

const managerPermissions = allPermissions.filter(
  (code) => !["roles.create", "roles.update", "settings.update"].includes(code),
);

const accountantPermissions = [
  "dashboard.read",
  "reports.read",
  "reports.export",
  "clients.read",
  "client_contacts.read",
  "notes.read",
  "notes.create",
  "notes.update",
  "quotations.read",
  "quotations.export_pdf",
  "invoices.read",
  "invoices.create",
  "invoices.update",
  "invoices.issue",
  "invoices.void",
  "invoices.export_pdf",
  "payments.read",
  "payments.record",
  "payments.allocate",
  "payments.update",
  "expenses.read",
  "expenses.create",
  "expenses.update",
  "expenses.approve",
  "expenses.pay",
  "projects.read",
  "files.read",
  "files.upload",
  "files.link",
  "catalog.read",
  "numbering_sequences.read",
  "numbering_sequences.update",
] as const;

const salesPermissions = [
  "dashboard.read",
  "reports.read",
  "clients.read",
  "clients.create",
  "clients.update",
  "client_contacts.read",
  "client_contacts.create",
  "client_contacts.update",
  "leads.read",
  "leads.create",
  "leads.update",
  "leads.archive",
  "leads.convert",
  "lead_activities.read",
  "lead_activities.create",
  "lead_activities.update",
  "notes.read",
  "notes.create",
  "notes.update",
  "quotations.read",
  "quotations.create",
  "quotations.update",
  "quotations.send",
  "quotations.reject",
  "quotations.duplicate",
  "quotations.export_pdf",
  "quotations.convert",
  "invoices.read",
  "invoices.export_pdf",
  "payments.read",
  "files.read",
  "files.upload",
  "files.link",
  "catalog.read",
  "catalog.create",
  "catalog.update",
] as const;

const workshopPermissions = [
  "dashboard.read",
  "reports.read",
  "clients.read",
  "client_contacts.read",
  "quotations.read",
  "quotations.export_pdf",
  "delivery_notes.read",
  "delivery_notes.create",
  "delivery_notes.update",
  "delivery_notes.change_status",
  "delivery_notes.export_pdf",
  "vehicles.read",
  "projects.read",
  "projects.create",
  "projects.update",
  "projects.change_status",
  "projects.assign",
  "project_stages.manage",
  "project_tasks.manage",
  "project_measurements.manage",
  "project_files.manage",
  "expenses.read",
  "expenses.create",
  "expenses.update",
  "files.read",
  "files.upload",
  "files.link",
  "catalog.read",
  "catalog.create",
  "catalog.update",
  "catalog.archive",
] as const;

const logisticsPermissions = [
  "dashboard.read",
  "clients.read",
  "client_contacts.read",
  "quotations.read",
  "quotations.export_pdf",
  "delivery_notes.read",
  "delivery_notes.create",
  "delivery_notes.update",
  "delivery_notes.change_status",
  "delivery_notes.export_pdf",
  "vehicles.read",
  "vehicles.create",
  "vehicles.update",
  "projects.read",
  "projects.update",
  "projects.change_status",
  "project_tasks.manage",
  "project_measurements.manage",
  "project_files.manage",
  "files.read",
  "files.upload",
  "files.link",
  "catalog.read",
  "reports.read",
] as const;

const viewerPermissions = [
  "dashboard.read",
  "reports.read",
  "clients.read",
  "client_contacts.read",
  "leads.read",
  "lead_activities.read",
  "notes.read",
  "quotations.read",
  "quotations.export_pdf",
  "invoices.read",
  "invoices.export_pdf",
  "payments.read",
  "expenses.read",
  "delivery_notes.read",
  "delivery_notes.export_pdf",
  "vehicles.read",
  "projects.read",
  "files.read",
  "catalog.read",
] as const;

export const roleTemplates: RoleTemplateSeed[] = [
  {
    code: "super_admin",
    name: "Super Admin",
    description: "Full tenant administration across all business and security modules.",
    defaultScope: "tenant",
    permissionCodes: allPermissions,
  },
  {
    code: "manager",
    name: "Manager",
    description: "Cross-module management role with approval and supervisory powers.",
    defaultScope: "tenant",
    permissionCodes: managerPermissions,
  },
  {
    code: "accountant",
    name: "Accountant",
    description: "Financial operations role for invoices, payments, allocations, expenses, and reporting.",
    defaultScope: "tenant",
    permissionCodes: [...accountantPermissions],
  },
  {
    code: "sales",
    name: "Sales",
    description: "Commercial role for leads, clients, quotations, and commercial follow-up.",
    defaultScope: "branch",
    permissionCodes: [...salesPermissions],
  },
  {
    code: "workshop_manager",
    name: "Workshop Manager",
    description: "Operational role for projects, fabrication stages, tasks, measurements, and execution files.",
    defaultScope: "branch",
    permissionCodes: [...workshopPermissions],
  },
  {
    code: "logistics_delivery",
    name: "Logistics / Delivery",
    description: "Dispatch and delivery role for transport, delivery notes, and delivery status tracking.",
    defaultScope: "branch",
    permissionCodes: [...logisticsPermissions],
  },
  {
    code: "employee_viewer",
    name: "Employee / Viewer",
    description: "Read-only or assigned-only access to operational and reference information.",
    defaultScope: "assigned",
    permissionCodes: [...viewerPermissions],
  },
];

